### ISSUE TITLE
RIDEV_INPUTSINK has wrong flag value

### ISSUE THREAD

**Issue by vmech** [TheArkive/MouseDelta_ahk2#1]
Must be `RIDEV_INPUTSINK := 0x00000100` instead of `0x00001100`.

Also, combining flags values is unacceptable:

`dwFlags`

Type: **DWORD**

Mode flag that specifies how to interpret the information provided by usUsagePage and usUsage. __It can be zero (the default) or one of the following values.__

[RAWINPUTDEVICE structure (winuser.h)](https://docs.microsoft.com/en-us/windows/win32/api/winuser/ns-winuser-rawinputdevice#members)

**Comment by TheArkive** [comment]
Changed.  Let me know if it works as desired and if you catch anything else.
