### ISSUE TITLE
A_LastError equal 87 every time the device is unregistered

### ISSUE THREAD

**Issue by vmech** [TheArkive/MouseDelta_ahk2#2]
The original class implemented by EvilC contains this issue.

If **RIDEV_REMOVE** is set and the **hwndTarget** member is not set to **NULL**, then RegisterRawInputDevices function will fail.

[RAWINPUTDEVICE structure (winuser.h)](https://docs.microsoft.com/en-us/windows/win32/api/winuser/ns-winuser-rawinputdevice#remarks)

```Autohotkey
RAWINPUTDEVICE := this.RAWINPUTDEVICE
NumPut("UInt", RIDEV_REMOVE, "Ptr", 0, RAWINPUTDEVICE, 4)
DllCall("RegisterRawInputDevices", "Ptr", RAWINPUTDEVICE.Ptr, "UInt", 1, "UInt", DevSize )
```

**Comment by TheArkive** [comment]
Thanks for this.  I actually had hwndTarget set to 0 in my private copy.  Not sure how I missed it on the repo.  It's working on my end.  No more error 87.  Let me know if you get the same.
